### ISSUE TITLE
User Story 29 Final Test

### ISSUE THREAD

**Issue by JorgenDIF** [JorgenDIF/PP5-RestInEase-Frontend#44]
As a **developer**, I want to **perform a comprehensive test of the deployed application**, so that I can **ensure everything works as expected**.

**Acceptance Criteria:**

1. Comprehensive tests are performed and pass successfully.

**Tasks:**

- [ ] Perform end-to-end testing in the production environment.
- [ ] Verify all functionalities and features.
- [ ] Fix any issues found during testing.
