### ISSUE TITLE
User Story 30 Final Mentor Session

### ISSUE THREAD

**Issue by JorgenDIF** [JorgenDIF/PP5-RestInEase-Frontend#45]
As a **developer**, I want to **present the deployed application to my mentor**, so that I can **get feedback and make any necessary adjustments**.

**Acceptance Criteria:**

1. Mentor feedback is documented and discussed.
2. Necessary adjustments are made based on feedback.

**Tasks:**

- [ ] Schedule and conduct the mentor meeting.
- [ ] Present the deployed application.
- [ ] Document and address mentor feedback.
